short/urls.py
from django.urls import path
from .views import urliew, ShortenedUrlView, works

urlpatterns = [
    path('', ShortenedUrlView.as_view(), name="main"),
    path('<uuid:id>', urliew, name="yeah"),
    path('works', works, name="works"),
]

shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('short.urls'))
]

short/models.py
from django.db import models
import string
import uuid
import random

from django.urls import reverse

def get_random_string():
    length = 7
    letters = string.ascii_letters + string.digits
    result = ''.join(random.choice(letters) for i in range(length))
    return result

# Create your models here.
class SHORTURL(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url_path = models.URLField(max_length=120, blank=True)
    orignalurl = models.CharField(max_length=600)
    created = models.DateTimeField(auto_now_add=True)
    expires = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self, *args, **kwargs):
        return reverse("yeah", args=[self.id])


    def __str__(self):
        return self.url_path

short/forms.py
from django import forms
from django.db.models.fields import Field
from .models import SHORTURL
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Field, Submit, Row, Field

class SHORTURLForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row (
                Column(Field("orignalurl", placeholder="Shorten You Link", css_class="form-control form-control-lg")),
                Column(Submit('submit', 'Shorten', css_class="btn btn-primary"),)
            )
        )
    class Meta:
        model = SHORTURL
        fields = ["orignalurl"]

short/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView
from .models import SHORTURL
from .forms import SHORTURLForm
from django.urls import reverse_lazy
from django.urls import reverse
from django.views.generic import DetailView, ListView
# Create your views here.

def urliew(request, id):
    url_shortened = get_object_or_404(SHORTURL, id=id)
    return redirect(url_shortened.orignalurl)

class ShortenedUrlView(CreateView):
    form_class = SHORTURLForm
    template_name = "home.html"
    success_url = reverse_lazy("main")
    def get_context_data(self, **kwargs):
        self.shortened_urls = SHORTURL.objects.all()
        kwargs['shortened_urls'] = self.shortened_urls
        return super().get_context_data(**kwargs)
    
    def form_valid(self, form):
        form.instance.url_path = self.request.build_absolute_uri(form.instance.get_absolute_url())
        return super().form_valid(form)

def works(request):
    template_name = "short/works.html"
    return render(request, template_name, {})

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>{% block title %}Bitoly{% endblock %}</title>
  </head>
  <style>
    .custom-file-label:focus {
      border: 1px solid #fec23d;
    }
    .nav-item {
      margin-right: 1.5rem;
      font-size: 0.95rem;
    }
    .misi input {
      margin-left: 10rem;
      margin-right: 10rem;
    }
    .terms {
      font-size: 0.7rem;
      margin-left: 15rem;
      color: #787f90!important;
    }
    .nino {
      display: inline;
    }
    .shtn {
      padding-left: 3rem;
      padding-right: 2.5rem;
    }
    .teco {
      font-size: 0.9rem!important;
      color: #585858;
    }
    .teco-title {
      font-weight: bolder;
    }
    .yego {
      color: #56575b;
      font-family: "ProximaNova Regular","Helvetica Neue",Helvetica,Arial,sans-serif;
      font-size: 20px;
      font-weight: normal;
      margin-top: -1.5rem;
    }
    .yego-title {
      color: #252628;
      font-family: "ProximaNova ExtraBold","Helvetica Neue",Helvetica,Arial,sans-serif;
      font-size: 38px;
      font-weight: 800;
      line-height: 40px;
    }
    .dropi-in {
      border: 1px solid rgb(0 0 0 / 8%);
      min-width: 25rem!important;
      margin-left: -10rem;
    }
    .dropi:hover {
      border-bottom: 3px solid red;
      transition: border-bottom 0.5s;
      -webkit-transition: border-bottom 0.5s linear;
      transform-style: preserve-3d;
    }
  </style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="{% static 'imgs/bitly.png' %}" class="rounded" alt="bitly" style="max-width: 6rem;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-right: 5rem; margin-left: 5rem;">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Why Bitly?</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Solutions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle dropi" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Pricing
              </a>
              <ul class="dropdown-menu dropi-in" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Resources</a>
            </li>
          </ul>
          <form class="d-flex">
            <a class="nav-link" href="#">Login</a>
            <a class="nav-link" href="#">Sign up Free</a>
            <button class="btn btn-sm btn-primary p-2" type="submit">Get a Quote</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="jumbotron">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        $('.toast').toast('show');
      });
    </script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row p-4 mt-5" style="max-height: 45rem;">
    <div class="col-md-6" style="padding: 3.3rem;">
        <h1 class="display-4" style="font-weight: bold;">Short links, big results</h1>
        <p class="lead text-muted">A URL shortener built with powerful tools to help you grow and protect your brand.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Get Started for Free</a>
    </div>
    <div class="col-md-6" style="background-image: url({% static 'imgs/dinos.jpg' %}); background-size: 700px 300px; background-repeat: no-repeat;">        
    </div>
</div>
<div class="d-flex justify-content-center shorten" style="background-color: #0b1736!important;">
    <div class="mt-5 w-75 p-3 mb-3">
        <form method="post" class="form-inline mb-3">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-10 my-1">
                    <input type="text" name="orignalurl" maxlength="600" class="form-control form-control-lg textinput textInput" placeholder="Shorten You Link" required="" id="id_orignalurl">
                </div>
                <div class="col-sm-2 my-l">
                    <input type="submit" name="submit" value="Shorten" class="btn btn-primary btn-lg btn-block shtn" id="submit-id-submit">
                </div>
            </div>
        </form>
        
        <p class="text-white terms">By clicking SHORTEN, you are agreeing to Bitoly’s Terms of Service and Privacy Policy</p>
        {% if shortened_urls %}
        <ul class="list-group bg-white">
            {% for short_url in shortened_urls%}
            <li class="list-group-item d-flex justify-content-between align-items-center border-0">
                {{ short_url.orignalurl|truncatechars:55 }}
                <div>
                    <a href="{{ short_url.get_absolute_url }}">{{ short_url.url_path }}</a>
                    <button class="btn btn-light copi">Copy</button>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

<div class="container w-75">
    <center class="p-5">
        <h3 class="yego-title">The link shortener that has your brand’s back</h3><br>
        <p class="yego">Your brand wasn’t built to be hidden. Help it stand out with branded links that drive 34% more clicks.</p>
    </center>
    <div class="row">
        <div class="col-md-4">
            <div class="card border-0" style="width: 20rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title teco-title">Inspire trust</h5>
                <p class="card-text teco">With more clicks comes increased brand recognition and consumer trust in your communications—which in turn inspires even more engagement with your links. (It’s a wonderful cycle.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card border-0" style="width: 20rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title teco-title">Gain control</h5>
                <p class="card-text teco">Take credit for your content and learn more about how it’s consumed by enabling auto-branding—a feature that ensures your brand remains in any link someone shortens pointing to your website.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card border-0" style="width: 20rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title teco-title">Boost results</h5>
                <p class="card-text teco">On top of better deliverability and click-through, rich link-level data gives you crucial insight into your link engagement so your team can make smarter decisions around its content and communications.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/short/works.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="alert alert-primary" role="alert">
    it works
</div>
{% endblock %}